#ifndef COMMUNICATIONCLIENTEXPORT_H
#define COMMUNICATIONCLIENTEXPORT_H

#include <QtCore/qglobal.h>

#if not defined(LIBRARY_UNEXPORT)
    #if defined(COMMUNICATIONCLIENT_LIBRARY)
    #  define COMMUNICATIONCLIENT_EXPORT Q_DECL_EXPORT
    #else
    #  define COMMUNICATIONCLIENT_EXPORT Q_DECL_IMPORT
    #endif
#else
    #  define COMMUNICATIONCLIENT_EXPORT
#endif

#endif // COMMUNICATIONCLIENTEXPORT_H
