
## user data about project path
USERDATA_PROJECT_ROOT = $$absolute_path($$PWD)
USERDATA_PROJECT_OUTPUT_ROOT = $$absolute_path($$OUT_PWD/builder)
## user data about development kit path
#USERDATA_DEVELOPMENT_KIT_ROOT = $$absolute_path($$USERDATA_PROJECT_ROOT/../..)
#USERDATA_DEVELOPMENT_KIT_COMMON_DIR = $$USERDATA_DEVELOPMENT_KIT_ROOT/common
#USERDATA_DEVELOPMENT_KIT_LIBRARY_DIR = $$USERDATA_DEVELOPMENT_KIT_ROOT/librarys
#USERDATA_DEVELOPMENT_KIT_THIRDPARTY_DIR = $$USERDATA_DEVELOPMENT_KIT_ROOT/thirdparty
## user data to set install dir and files
USERDATA_INSTALL_DIR = $$USERDATA_PROJECT_OUTPUT_ROOT/libs
#USERDATA_DEPEND_DIR = $$USERDATA_PROJECT_OUTPUT_ROOT/libs

include($$USERDATA_PROJECT_ROOT/CommunicationClient.pri)
